baseURL = 'https://saverio976.github.io/'

defaultContentLanguage = 'en'
languageCode = "en-us"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = 'Saverio976'

enableEmoji = true

theme = 'hermit-V2'
enableRobotsTXT = true

[frontmatter]
  date = ["lastmod", "date", "publishDate"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[params.author]
  name = "Saverio976"


[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
[markup.highlight]
  lineNos = false
  lineNumbersInTable = false
  noClasses = true

[languages.en]
  title = "Saverio976"
  languageName = "English"
  contentDir = "content"
[languages.en.params]
  homeSubtitle = "I do things because why not"

[params]
  #maybe not used
  homeSubtitle = "I do things because why not"
  description = "I do things because why not"
  # images = [""]
  themeColor = "#494f5c"
  accentColor = "#018472"

  footerCopyright = "CC-by"
  footerHideThemeName = false
  # bgImg = ""
  gitUrl = "https://github.com/Saverio976/Saverio976.github.io"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "Read Time: "
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # listLayout = ["description","tags","categories","legacy"]
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  usesAnimation = true
  # mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  # mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
  [params.gallery]
    enable = true
    thumbnail = '300'

  [params.dateform]
    CopyrightDate = "2006"
    LongDate = "Jan 2, 2006"
    ShortDate = "Jan 2"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04 -0700"


  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/Saverio976"
  [[params.socialLinks]]
    name = "gitlab"
    url = "https://gitlab.com/Saverio976"
